version: '3.8'

services:
  database:
    image: postgres:17.2
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=adminpassword
      - POSTGRES_DB=livechat
    ports:
      - "15432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    
  backend:
    build: ./backend
    restart: always
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgresql://admin:adminpassword@database:5432/livechat
      - JWT_SECRET=94EBC4537FB849388DACE2399FE9F1ADF1ADA34BDA3852D5E2868993CD
      - PORT=4000
    ports:
      - "14000:4000"
      - "8080:80"
    volumes:
      - ./backend:/app
      - /app/node_modules/bcrypt/ # INFO: Bcrypt w/ Docker Context causes issue. We need to bind the volume to prevent Docker to copy it from local.
    command: sh -c "npm run migration:run && npm run start:dev"

  frontend-admin:
    build:
      context: ./frontend/admin
      dockerfile: ./Dockerfile
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/admin:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host"
    stdin_open: true
    tty: true

  frontend-client:
    build:
      context: ./frontend/client
      dockerfile: ./Dockerfile
    restart: always
    depends_on:
      - backend
    ports:
      - "5174:5173"
    volumes:
      - ./frontend/client:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host"
    stdin_open: true
    tty: true

volumes:
  db-data:
